name: tmdb
description: Dart wrapper for TMDB's API (themoviedb.org).
version: 0.0.1
author: Josep Sayol <josep.sayol@gmail.com>
homepage: https://github.com/jsayol/dart-tmdb

environment:
  sdk: '>=1.0.0 <2.0.0'

# dependencies:
#   http: '^0.11.3'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
